# This Makefile is not used by the Spade flow but we leave it here to be able to use
# the GDS action to set up everything else

gate:
	cp results-dummy.xml results.xml

clean:
	echo "Makefile is unused"

# # RTL simulation:
# SIM_BUILD				= sim_build/rtl
# VERILOG_SOURCES += $(addprefix $(SRC_DIR)/,$(PROJECT_SOURCES))
# 
# else
# 
# # Gate level simulation:
# SIM_BUILD				= sim_build/gl
# COMPILE_ARGS    += -DGL_TEST
# COMPILE_ARGS    += -DFUNCTIONAL
# COMPILE_ARGS    += -DSIM
# VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v
# VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v
# 
# # this gets copied in by the GDS action workflow
# VERILOG_SOURCES += $(PWD)/gate_level_netlist.v
# 
# endif
# 
# # Allow sharing configuration between design and testbench via `include`:
# COMPILE_ARGS 		+= -I$(SRC_DIR)
# 
# # Include the testbench sources:
# VERILOG_SOURCES += $(PWD)/tb.v
# TOPLEVEL = tb
# 
# # List test modules to run, separated by commas and without the .py suffix:
# COCOTB_TEST_MODULES = test
# 
# # include cocotb's make rules to take care of the simulator setup
# include $(shell cocotb-config --makefiles)/Makefile.sim
